package com.wedding.sync.mapper;

import com.wedding.sync.pojo.DataSync;
import com.wedding.sync.pojo.DataSyncExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataSyncMapper {
	
	List<DataSync> findAll(Integer max);
	
	List<DataSync> findAllErrRecord(@Param("start")Integer start, @Param("max")Integer max);
	
	int updateErrorInfo(@Param("id")Integer id, @Param("info")String info);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int countByExample(DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int deleteByExample(DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int insert(DataSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int insertSelective(DataSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    List<DataSync> selectByExample(DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    DataSync selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") DataSync record, @Param("example") DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int updateByExample(@Param("record") DataSync record, @Param("example") DataSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int updateByPrimaryKeySelective(DataSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_data_sync
     *
     * @mbggenerated Sat Nov 08 14:30:20 CST 2014
     */
    int updateByPrimaryKey(DataSync record);
}