package com.wedding.user.pojo;

import java.util.Date;

public class AdminAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.id
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.user_name
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.passwd
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.company_id
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.group
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private String group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.create_time
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.create_person
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.last_update_time
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.last_update_person
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_admin_account.stat
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.id
     *
     * @return the value of wd_admin_account.id
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.id
     *
     * @param id the value for wd_admin_account.id
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.user_name
     *
     * @return the value of wd_admin_account.user_name
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.user_name
     *
     * @param userName the value for wd_admin_account.user_name
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.passwd
     *
     * @return the value of wd_admin_account.passwd
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.passwd
     *
     * @param passwd the value for wd_admin_account.passwd
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.company_id
     *
     * @return the value of wd_admin_account.company_id
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.company_id
     *
     * @param companyId the value for wd_admin_account.company_id
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.group
     *
     * @return the value of wd_admin_account.group
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.group
     *
     * @param group the value for wd_admin_account.group
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.create_time
     *
     * @return the value of wd_admin_account.create_time
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.create_time
     *
     * @param createTime the value for wd_admin_account.create_time
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.create_person
     *
     * @return the value of wd_admin_account.create_person
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.create_person
     *
     * @param createPerson the value for wd_admin_account.create_person
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.last_update_time
     *
     * @return the value of wd_admin_account.last_update_time
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.last_update_time
     *
     * @param lastUpdateTime the value for wd_admin_account.last_update_time
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.last_update_person
     *
     * @return the value of wd_admin_account.last_update_person
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.last_update_person
     *
     * @param lastUpdatePerson the value for wd_admin_account.last_update_person
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_admin_account.stat
     *
     * @return the value of wd_admin_account.stat
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_admin_account.stat
     *
     * @param stat the value for wd_admin_account.stat
     *
     * @mbggenerated Wed Aug 27 23:36:15 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}