package com.wedding.order.pojo;

import java.util.Date;

public class OrderItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.order_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.item_name
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.quantity
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.active_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private Integer activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.item_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.discount_fee
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private Integer discountFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.item_total
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private Integer itemTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.create_time
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.create_person
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.last_update_time
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.last_update_person
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_order_items.stat
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.id
     *
     * @return the value of wd_order_items.id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.id
     *
     * @param id the value for wd_order_items.id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.order_id
     *
     * @return the value of wd_order_items.order_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.order_id
     *
     * @param orderId the value for wd_order_items.order_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.item_name
     *
     * @return the value of wd_order_items.item_name
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.item_name
     *
     * @param itemName the value for wd_order_items.item_name
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.quantity
     *
     * @return the value of wd_order_items.quantity
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.quantity
     *
     * @param quantity the value for wd_order_items.quantity
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.active_id
     *
     * @return the value of wd_order_items.active_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public Integer getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.active_id
     *
     * @param activeId the value for wd_order_items.active_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setActiveId(Integer activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.item_id
     *
     * @return the value of wd_order_items.item_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.item_id
     *
     * @param itemId the value for wd_order_items.item_id
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.discount_fee
     *
     * @return the value of wd_order_items.discount_fee
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public Integer getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.discount_fee
     *
     * @param discountFee the value for wd_order_items.discount_fee
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setDiscountFee(Integer discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.item_total
     *
     * @return the value of wd_order_items.item_total
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public Integer getItemTotal() {
        return itemTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.item_total
     *
     * @param itemTotal the value for wd_order_items.item_total
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setItemTotal(Integer itemTotal) {
        this.itemTotal = itemTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.create_time
     *
     * @return the value of wd_order_items.create_time
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.create_time
     *
     * @param createTime the value for wd_order_items.create_time
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.create_person
     *
     * @return the value of wd_order_items.create_person
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.create_person
     *
     * @param createPerson the value for wd_order_items.create_person
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.last_update_time
     *
     * @return the value of wd_order_items.last_update_time
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.last_update_time
     *
     * @param lastUpdateTime the value for wd_order_items.last_update_time
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.last_update_person
     *
     * @return the value of wd_order_items.last_update_person
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.last_update_person
     *
     * @param lastUpdatePerson the value for wd_order_items.last_update_person
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_order_items.stat
     *
     * @return the value of wd_order_items.stat
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_order_items.stat
     *
     * @param stat the value for wd_order_items.stat
     *
     * @mbggenerated Fri Sep 19 10:45:17 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}