package com.wedding.tools.pojo;

public class AddressesView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.proid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private Integer proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.proname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private String proname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.prolev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private Short prolev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.cityid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.cityname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.citylev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private Short citylev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.regionid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private Integer regionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.regionname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private String regionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.regionlev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private Short regionlev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses_view.parent_id
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.proid
     *
     * @return the value of wd_addresses_view.proid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.proid
     *
     * @param proid the value for wd_addresses_view.proid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.proname
     *
     * @return the value of wd_addresses_view.proname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.proname
     *
     * @param proname the value for wd_addresses_view.proname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.prolev
     *
     * @return the value of wd_addresses_view.prolev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public Short getProlev() {
        return prolev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.prolev
     *
     * @param prolev the value for wd_addresses_view.prolev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setProlev(Short prolev) {
        this.prolev = prolev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.cityid
     *
     * @return the value of wd_addresses_view.cityid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.cityid
     *
     * @param cityid the value for wd_addresses_view.cityid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.cityname
     *
     * @return the value of wd_addresses_view.cityname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.cityname
     *
     * @param cityname the value for wd_addresses_view.cityname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.citylev
     *
     * @return the value of wd_addresses_view.citylev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public Short getCitylev() {
        return citylev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.citylev
     *
     * @param citylev the value for wd_addresses_view.citylev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setCitylev(Short citylev) {
        this.citylev = citylev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.regionid
     *
     * @return the value of wd_addresses_view.regionid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public Integer getRegionid() {
        return regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.regionid
     *
     * @param regionid the value for wd_addresses_view.regionid
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setRegionid(Integer regionid) {
        this.regionid = regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.regionname
     *
     * @return the value of wd_addresses_view.regionname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public String getRegionname() {
        return regionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.regionname
     *
     * @param regionname the value for wd_addresses_view.regionname
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setRegionname(String regionname) {
        this.regionname = regionname == null ? null : regionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.regionlev
     *
     * @return the value of wd_addresses_view.regionlev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public Short getRegionlev() {
        return regionlev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.regionlev
     *
     * @param regionlev the value for wd_addresses_view.regionlev
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setRegionlev(Short regionlev) {
        this.regionlev = regionlev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses_view.parent_id
     *
     * @return the value of wd_addresses_view.parent_id
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses_view.parent_id
     *
     * @param parentId the value for wd_addresses_view.parent_id
     *
     * @mbggenerated Fri Oct 10 14:42:56 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}