package com.wedding.tools.pojo;

public class Addresses {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses.id
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses.parent_id
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses.name
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_addresses.level
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    private Short level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses.id
     *
     * @return the value of wd_addresses.id
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses.id
     *
     * @param id the value for wd_addresses.id
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses.parent_id
     *
     * @return the value of wd_addresses.parent_id
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses.parent_id
     *
     * @param parentId the value for wd_addresses.parent_id
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses.name
     *
     * @return the value of wd_addresses.name
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses.name
     *
     * @param name the value for wd_addresses.name
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_addresses.level
     *
     * @return the value of wd_addresses.level
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_addresses.level
     *
     * @param level the value for wd_addresses.level
     *
     * @mbggenerated Mon Oct 13 11:34:37 CST 2014
     */
    public void setLevel(Short level) {
        this.level = level;
    }
}