package com.wedding.tools.pojo;

import java.util.Date;

public class ToolsNote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.id
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.type
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.plan_day
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private Integer planDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.context
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.stat
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.create_time
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.create_person
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.last_update_time
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_tools_note.last_update_person
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.id
     *
     * @return the value of wd_tools_note.id
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.id
     *
     * @param id the value for wd_tools_note.id
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.type
     *
     * @return the value of wd_tools_note.type
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.type
     *
     * @param type the value for wd_tools_note.type
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.plan_day
     *
     * @return the value of wd_tools_note.plan_day
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public Integer getPlanDay() {
        return planDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.plan_day
     *
     * @param planDay the value for wd_tools_note.plan_day
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setPlanDay(Integer planDay) {
        this.planDay = planDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.context
     *
     * @return the value of wd_tools_note.context
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.context
     *
     * @param context the value for wd_tools_note.context
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.stat
     *
     * @return the value of wd_tools_note.stat
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.stat
     *
     * @param stat the value for wd_tools_note.stat
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.create_time
     *
     * @return the value of wd_tools_note.create_time
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.create_time
     *
     * @param createTime the value for wd_tools_note.create_time
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.create_person
     *
     * @return the value of wd_tools_note.create_person
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.create_person
     *
     * @param createPerson the value for wd_tools_note.create_person
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.last_update_time
     *
     * @return the value of wd_tools_note.last_update_time
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.last_update_time
     *
     * @param lastUpdateTime the value for wd_tools_note.last_update_time
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_tools_note.last_update_person
     *
     * @return the value of wd_tools_note.last_update_person
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_tools_note.last_update_person
     *
     * @param lastUpdatePerson the value for wd_tools_note.last_update_person
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }
}