package com.wedding.items.mapper;

import com.wedding.items.pojo.Items;
import com.wedding.items.pojo.ItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int countByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int deleteByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int insert(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int insertSelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    List<Items> selectByExample(ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    Items selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int updateByExampleSelective(@Param("record") Items record, @Param("example") ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int updateByExample(@Param("record") Items record, @Param("example") ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int updateByPrimaryKeySelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items
     *
     * @mbggenerated Mon Jan 12 17:16:13 CST 2015
     */
    int updateByPrimaryKey(Items record);
}