package com.wedding.items.mapper;

import com.wedding.items.pojo.ItemsTypeProperties;
import com.wedding.items.pojo.ItemsTypePropertiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemsTypePropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int countByExample(ItemsTypePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int deleteByExample(ItemsTypePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int insert(ItemsTypeProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int insertSelective(ItemsTypeProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    List<ItemsTypeProperties> selectByExample(ItemsTypePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    ItemsTypeProperties selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int updateByExampleSelective(@Param("record") ItemsTypeProperties record, @Param("example") ItemsTypePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int updateByExample(@Param("record") ItemsTypeProperties record, @Param("example") ItemsTypePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int updateByPrimaryKeySelective(ItemsTypeProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_type_properties
     *
     * @mbggenerated Sun Nov 02 14:02:18 CST 2014
     */
    int updateByPrimaryKey(ItemsTypeProperties record);
}