package com.wedding.items.mapper;

import com.wedding.items.pojo.ItemsDesc;
import com.wedding.items.pojo.ItemsDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemsDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int countByExample(ItemsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int deleteByExample(ItemsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int insert(ItemsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int insertSelective(ItemsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    List<ItemsDesc> selectByExampleWithBLOBs(ItemsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    List<ItemsDesc> selectByExample(ItemsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    ItemsDesc selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int updateByExampleSelective(@Param("record") ItemsDesc record, @Param("example") ItemsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") ItemsDesc record, @Param("example") ItemsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int updateByExample(@Param("record") ItemsDesc record, @Param("example") ItemsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int updateByPrimaryKeySelective(ItemsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(ItemsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    int updateByPrimaryKey(ItemsDesc record);
}