package com.wedding.order.mapper;

import com.wedding.order.pojo.Appoint;
import com.wedding.order.pojo.AppointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int countByExample(AppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int deleteByExample(AppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int insert(Appoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int insertSelective(Appoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    List<Appoint> selectByExample(AppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    Appoint selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int updateByExampleSelective(@Param("record") Appoint record, @Param("example") AppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int updateByExample(@Param("record") Appoint record, @Param("example") AppointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int updateByPrimaryKeySelective(Appoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_appoint
     *
     * @mbggenerated Sat Sep 20 22:40:01 CST 2014
     */
    int updateByPrimaryKey(Appoint record);
}