package com.wedding.order.mapper;

import com.wedding.order.pojo.WithDraw;
import com.wedding.order.pojo.WithDrawExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithDrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int countByExample(WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int deleteByExample(WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int insert(WithDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int insertSelective(WithDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    List<WithDraw> selectByExample(WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    WithDraw selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int updateByExampleSelective(@Param("record") WithDraw record, @Param("example") WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int updateByExample(@Param("record") WithDraw record, @Param("example") WithDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int updateByPrimaryKeySelective(WithDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_withdraw
     *
     * @mbggenerated Mon Sep 29 10:27:38 CST 2014
     */
    int updateByPrimaryKey(WithDraw record);
}