package com.wedding.user.mapper;

import com.wedding.user.pojo.UserSite;
import com.wedding.user.pojo.UserSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int countByExample(UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int deleteByExample(UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int insert(UserSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int insertSelective(UserSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    List<UserSite> selectByExample(UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    UserSite selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserSite record, @Param("example") UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int updateByExample(@Param("record") UserSite record, @Param("example") UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int updateByPrimaryKeySelective(UserSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site
     *
     * @mbggenerated Wed Sep 17 21:52:47 CST 2014
     */
    int updateByPrimaryKey(UserSite record);
}