package com.wedding.user.mapper;

import com.wedding.user.pojo.UserSiteTotal;
import com.wedding.user.pojo.UserSiteTotalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSiteTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    int countByExample(UserSiteTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    int deleteByExample(UserSiteTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    int insert(UserSiteTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    int insertSelective(UserSiteTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    List<UserSiteTotal> selectByExample(UserSiteTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:06 CST 2014
     */
    UserSiteTotal selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:06 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserSiteTotal record, @Param("example") UserSiteTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:06 CST 2014
     */
    int updateByExample(@Param("record") UserSiteTotal record, @Param("example") UserSiteTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:06 CST 2014
     */
    int updateByPrimaryKeySelective(UserSiteTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_site_total
     *
     * @mbggenerated Thu Oct 09 15:57:06 CST 2014
     */
    int updateByPrimaryKey(UserSiteTotal record);
}