package com.wedding.tools.mapper;

import com.wedding.tools.pojo.ToolsNote;
import com.wedding.tools.pojo.ToolsNoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ToolsNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int countByExample(ToolsNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int deleteByExample(ToolsNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int insert(ToolsNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int insertSelective(ToolsNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    List<ToolsNote> selectByExample(ToolsNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    ToolsNote selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int updateByExampleSelective(@Param("record") ToolsNote record, @Param("example") ToolsNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int updateByExample(@Param("record") ToolsNote record, @Param("example") ToolsNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int updateByPrimaryKeySelective(ToolsNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_tools_note
     *
     * @mbggenerated Fri Sep 26 13:50:20 CST 2014
     */
    int updateByPrimaryKey(ToolsNote record);
}