package com.wedding.home.pojo;

import java.util.Date;

public class HomePageConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.id
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.data_key
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private String dataKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.data_value
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private String dataValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.order_tag
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private Integer orderTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.create_time
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.create_person
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.last_update_time
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.last_update_person
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_home_page_config.stat
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.id
     *
     * @return the value of wd_home_page_config.id
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.id
     *
     * @param id the value for wd_home_page_config.id
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.data_key
     *
     * @return the value of wd_home_page_config.data_key
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public String getDataKey() {
        return dataKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.data_key
     *
     * @param dataKey the value for wd_home_page_config.data_key
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setDataKey(String dataKey) {
        this.dataKey = dataKey == null ? null : dataKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.data_value
     *
     * @return the value of wd_home_page_config.data_value
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public String getDataValue() {
        return dataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.data_value
     *
     * @param dataValue the value for wd_home_page_config.data_value
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setDataValue(String dataValue) {
        this.dataValue = dataValue == null ? null : dataValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.order_tag
     *
     * @return the value of wd_home_page_config.order_tag
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public Integer getOrderTag() {
        return orderTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.order_tag
     *
     * @param orderTag the value for wd_home_page_config.order_tag
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setOrderTag(Integer orderTag) {
        this.orderTag = orderTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.create_time
     *
     * @return the value of wd_home_page_config.create_time
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.create_time
     *
     * @param createTime the value for wd_home_page_config.create_time
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.create_person
     *
     * @return the value of wd_home_page_config.create_person
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.create_person
     *
     * @param createPerson the value for wd_home_page_config.create_person
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.last_update_time
     *
     * @return the value of wd_home_page_config.last_update_time
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.last_update_time
     *
     * @param lastUpdateTime the value for wd_home_page_config.last_update_time
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.last_update_person
     *
     * @return the value of wd_home_page_config.last_update_person
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.last_update_person
     *
     * @param lastUpdatePerson the value for wd_home_page_config.last_update_person
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_home_page_config.stat
     *
     * @return the value of wd_home_page_config.stat
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_home_page_config.stat
     *
     * @param stat the value for wd_home_page_config.stat
     *
     * @mbggenerated Wed Nov 26 16:23:00 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}