package com.wedding.domain.pojo;

import java.util.Date;

public class Domain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_domain.id
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_domain.domain_name
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    private String domainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_domain.domain
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_domain.create_time
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_domain.create_person
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_domain.last_update_time
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_domain.last_update_person
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_domain.stat
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_domain.id
     *
     * @return the value of wd_domain.id
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_domain.id
     *
     * @param id the value for wd_domain.id
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_domain.domain_name
     *
     * @return the value of wd_domain.domain_name
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_domain.domain_name
     *
     * @param domainName the value for wd_domain.domain_name
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName == null ? null : domainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_domain.domain
     *
     * @return the value of wd_domain.domain
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_domain.domain
     *
     * @param domain the value for wd_domain.domain
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_domain.create_time
     *
     * @return the value of wd_domain.create_time
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_domain.create_time
     *
     * @param createTime the value for wd_domain.create_time
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_domain.create_person
     *
     * @return the value of wd_domain.create_person
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_domain.create_person
     *
     * @param createPerson the value for wd_domain.create_person
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_domain.last_update_time
     *
     * @return the value of wd_domain.last_update_time
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_domain.last_update_time
     *
     * @param lastUpdateTime the value for wd_domain.last_update_time
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_domain.last_update_person
     *
     * @return the value of wd_domain.last_update_person
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_domain.last_update_person
     *
     * @param lastUpdatePerson the value for wd_domain.last_update_person
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_domain.stat
     *
     * @return the value of wd_domain.stat
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_domain.stat
     *
     * @param stat the value for wd_domain.stat
     *
     * @mbggenerated Wed Oct 15 15:07:04 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}