package com.wedding.seller.mapper;

import com.wedding.seller.pojo.SellerProfile;
import com.wedding.seller.pojo.SellerProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellerProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int countByExample(SellerProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int deleteByExample(SellerProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int insert(SellerProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int insertSelective(SellerProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    List<SellerProfile> selectByExample(SellerProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    SellerProfile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int updateByExampleSelective(@Param("record") SellerProfile record, @Param("example") SellerProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int updateByExample(@Param("record") SellerProfile record, @Param("example") SellerProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int updateByPrimaryKeySelective(SellerProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_seller_profile
     *
     * @mbggenerated Tue Oct 14 16:19:04 CST 2014
     */
    int updateByPrimaryKey(SellerProfile record);
}