package com.wedding.items.pojo;

import java.util.Date;

public class ItemsDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.id
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.item_desc_key
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private String itemDescKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.item_desc_value
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private String itemDescValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.item_id
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.create_time
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.create_person
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.last_update_time
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.last_update_person
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.stat
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_items_desc.item_desc_text_value
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    private String itemDescTextValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.id
     *
     * @return the value of wd_items_desc.id
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.id
     *
     * @param id the value for wd_items_desc.id
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.item_desc_key
     *
     * @return the value of wd_items_desc.item_desc_key
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public String getItemDescKey() {
        return itemDescKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.item_desc_key
     *
     * @param itemDescKey the value for wd_items_desc.item_desc_key
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setItemDescKey(String itemDescKey) {
        this.itemDescKey = itemDescKey == null ? null : itemDescKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.item_desc_value
     *
     * @return the value of wd_items_desc.item_desc_value
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public String getItemDescValue() {
        return itemDescValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.item_desc_value
     *
     * @param itemDescValue the value for wd_items_desc.item_desc_value
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setItemDescValue(String itemDescValue) {
        this.itemDescValue = itemDescValue == null ? null : itemDescValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.item_id
     *
     * @return the value of wd_items_desc.item_id
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.item_id
     *
     * @param itemId the value for wd_items_desc.item_id
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.create_time
     *
     * @return the value of wd_items_desc.create_time
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.create_time
     *
     * @param createTime the value for wd_items_desc.create_time
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.create_person
     *
     * @return the value of wd_items_desc.create_person
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.create_person
     *
     * @param createPerson the value for wd_items_desc.create_person
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.last_update_time
     *
     * @return the value of wd_items_desc.last_update_time
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.last_update_time
     *
     * @param lastUpdateTime the value for wd_items_desc.last_update_time
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.last_update_person
     *
     * @return the value of wd_items_desc.last_update_person
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.last_update_person
     *
     * @param lastUpdatePerson the value for wd_items_desc.last_update_person
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.stat
     *
     * @return the value of wd_items_desc.stat
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.stat
     *
     * @param stat the value for wd_items_desc.stat
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_items_desc.item_desc_text_value
     *
     * @return the value of wd_items_desc.item_desc_text_value
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public String getItemDescTextValue() {
        return itemDescTextValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_items_desc.item_desc_text_value
     *
     * @param itemDescTextValue the value for wd_items_desc.item_desc_text_value
     *
     * @mbggenerated Thu Oct 23 17:36:29 CST 2014
     */
    public void setItemDescTextValue(String itemDescTextValue) {
        this.itemDescTextValue = itemDescTextValue == null ? null : itemDescTextValue.trim();
    }
}