package com.wedding.items.pojo;

import java.util.ArrayList;
import java.util.List;

public class ItemsDescExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public ItemsDescExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyIsNull() {
            addCriterion("item_desc_key is null");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyIsNotNull() {
            addCriterion("item_desc_key is not null");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyEqualTo(String value) {
            addCriterion("item_desc_key =", value, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyNotEqualTo(String value) {
            addCriterion("item_desc_key <>", value, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyGreaterThan(String value) {
            addCriterion("item_desc_key >", value, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyGreaterThanOrEqualTo(String value) {
            addCriterion("item_desc_key >=", value, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyLessThan(String value) {
            addCriterion("item_desc_key <", value, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyLessThanOrEqualTo(String value) {
            addCriterion("item_desc_key <=", value, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyLike(String value) {
            addCriterion("item_desc_key like", value, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyNotLike(String value) {
            addCriterion("item_desc_key not like", value, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyIn(List<String> values) {
            addCriterion("item_desc_key in", values, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyNotIn(List<String> values) {
            addCriterion("item_desc_key not in", values, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyBetween(String value1, String value2) {
            addCriterion("item_desc_key between", value1, value2, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescKeyNotBetween(String value1, String value2) {
            addCriterion("item_desc_key not between", value1, value2, "itemDescKey");
            return (Criteria) this;
        }

        public Criteria andItemDescValueIsNull() {
            addCriterion("item_desc_value is null");
            return (Criteria) this;
        }

        public Criteria andItemDescValueIsNotNull() {
            addCriterion("item_desc_value is not null");
            return (Criteria) this;
        }

        public Criteria andItemDescValueEqualTo(String value) {
            addCriterion("item_desc_value =", value, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueNotEqualTo(String value) {
            addCriterion("item_desc_value <>", value, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueGreaterThan(String value) {
            addCriterion("item_desc_value >", value, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueGreaterThanOrEqualTo(String value) {
            addCriterion("item_desc_value >=", value, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueLessThan(String value) {
            addCriterion("item_desc_value <", value, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueLessThanOrEqualTo(String value) {
            addCriterion("item_desc_value <=", value, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueLike(String value) {
            addCriterion("item_desc_value like", value, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueNotLike(String value) {
            addCriterion("item_desc_value not like", value, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueIn(List<String> values) {
            addCriterion("item_desc_value in", values, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueNotIn(List<String> values) {
            addCriterion("item_desc_value not in", values, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueBetween(String value1, String value2) {
            addCriterion("item_desc_value between", value1, value2, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemDescValueNotBetween(String value1, String value2) {
            addCriterion("item_desc_value not between", value1, value2, "itemDescValue");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(String value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(String value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(String value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(String value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(String value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLike(String value) {
            addCriterion("item_id like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotLike(String value) {
            addCriterion("item_id not like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<String> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<String> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(String value1, String value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(String value1, String value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_items_desc
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 17 22:47:53 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_items_desc
     *
     * @mbggenerated Wed Sep 17 22:47:53 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}