package com.wedding.seller.pojo;

import java.util.Date;

public class ShopSite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.shop_id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.integral
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.qq
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.domain_id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.create_time
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.create_person
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.last_update_time
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.last_update_person
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_shop_site.stat
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.id
     *
     * @return the value of wd_shop_site.id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.id
     *
     * @param id the value for wd_shop_site.id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.shop_id
     *
     * @return the value of wd_shop_site.shop_id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.shop_id
     *
     * @param shopId the value for wd_shop_site.shop_id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.integral
     *
     * @return the value of wd_shop_site.integral
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.integral
     *
     * @param integral the value for wd_shop_site.integral
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.qq
     *
     * @return the value of wd_shop_site.qq
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.qq
     *
     * @param qq the value for wd_shop_site.qq
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.domain_id
     *
     * @return the value of wd_shop_site.domain_id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.domain_id
     *
     * @param domainId the value for wd_shop_site.domain_id
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId == null ? null : domainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.create_time
     *
     * @return the value of wd_shop_site.create_time
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.create_time
     *
     * @param createTime the value for wd_shop_site.create_time
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.create_person
     *
     * @return the value of wd_shop_site.create_person
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.create_person
     *
     * @param createPerson the value for wd_shop_site.create_person
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.last_update_time
     *
     * @return the value of wd_shop_site.last_update_time
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.last_update_time
     *
     * @param lastUpdateTime the value for wd_shop_site.last_update_time
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.last_update_person
     *
     * @return the value of wd_shop_site.last_update_person
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.last_update_person
     *
     * @param lastUpdatePerson the value for wd_shop_site.last_update_person
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_shop_site.stat
     *
     * @return the value of wd_shop_site.stat
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_shop_site.stat
     *
     * @param stat the value for wd_shop_site.stat
     *
     * @mbggenerated Wed Oct 15 15:35:58 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}