package com.wedding.user.pojo;

import java.util.Date;

public class UserFavorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.shop_site_id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private String shopSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.user_id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.content
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.create_time
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.create_person
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.last_update_time
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.last_update_person
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_favorite.stat
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.id
     *
     * @return the value of wd_user_favorite.id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.id
     *
     * @param id the value for wd_user_favorite.id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.shop_site_id
     *
     * @return the value of wd_user_favorite.shop_site_id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public String getShopSiteId() {
        return shopSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.shop_site_id
     *
     * @param shopSiteId the value for wd_user_favorite.shop_site_id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setShopSiteId(String shopSiteId) {
        this.shopSiteId = shopSiteId == null ? null : shopSiteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.user_id
     *
     * @return the value of wd_user_favorite.user_id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.user_id
     *
     * @param userId the value for wd_user_favorite.user_id
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.content
     *
     * @return the value of wd_user_favorite.content
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.content
     *
     * @param content the value for wd_user_favorite.content
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.create_time
     *
     * @return the value of wd_user_favorite.create_time
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.create_time
     *
     * @param createTime the value for wd_user_favorite.create_time
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.create_person
     *
     * @return the value of wd_user_favorite.create_person
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.create_person
     *
     * @param createPerson the value for wd_user_favorite.create_person
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.last_update_time
     *
     * @return the value of wd_user_favorite.last_update_time
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.last_update_time
     *
     * @param lastUpdateTime the value for wd_user_favorite.last_update_time
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.last_update_person
     *
     * @return the value of wd_user_favorite.last_update_person
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.last_update_person
     *
     * @param lastUpdatePerson the value for wd_user_favorite.last_update_person
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_favorite.stat
     *
     * @return the value of wd_user_favorite.stat
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_favorite.stat
     *
     * @param stat the value for wd_user_favorite.stat
     *
     * @mbggenerated Sat Oct 04 19:30:06 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}