package com.wedding.user.pojo;

import java.util.Date;

public class UserSiteTotal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.id
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.view_count
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.site_id
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.view_year
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String viewYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.view_month
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String viewMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.view_day
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String viewDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.view_date
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String viewDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.create_time
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.create_person
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.last_update_time
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.last_update_person
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.stat
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_site_total.ip
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.id
     *
     * @return the value of wd_user_site_total.id
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.id
     *
     * @param id the value for wd_user_site_total.id
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.view_count
     *
     * @return the value of wd_user_site_total.view_count
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.view_count
     *
     * @param viewCount the value for wd_user_site_total.view_count
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.site_id
     *
     * @return the value of wd_user_site_total.site_id
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.site_id
     *
     * @param siteId the value for wd_user_site_total.site_id
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId == null ? null : siteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.view_year
     *
     * @return the value of wd_user_site_total.view_year
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getViewYear() {
        return viewYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.view_year
     *
     * @param viewYear the value for wd_user_site_total.view_year
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setViewYear(String viewYear) {
        this.viewYear = viewYear == null ? null : viewYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.view_month
     *
     * @return the value of wd_user_site_total.view_month
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getViewMonth() {
        return viewMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.view_month
     *
     * @param viewMonth the value for wd_user_site_total.view_month
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setViewMonth(String viewMonth) {
        this.viewMonth = viewMonth == null ? null : viewMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.view_day
     *
     * @return the value of wd_user_site_total.view_day
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getViewDay() {
        return viewDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.view_day
     *
     * @param viewDay the value for wd_user_site_total.view_day
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setViewDay(String viewDay) {
        this.viewDay = viewDay == null ? null : viewDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.view_date
     *
     * @return the value of wd_user_site_total.view_date
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getViewDate() {
        return viewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.view_date
     *
     * @param viewDate the value for wd_user_site_total.view_date
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setViewDate(String viewDate) {
        this.viewDate = viewDate == null ? null : viewDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.create_time
     *
     * @return the value of wd_user_site_total.create_time
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.create_time
     *
     * @param createTime the value for wd_user_site_total.create_time
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.create_person
     *
     * @return the value of wd_user_site_total.create_person
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.create_person
     *
     * @param createPerson the value for wd_user_site_total.create_person
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.last_update_time
     *
     * @return the value of wd_user_site_total.last_update_time
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.last_update_time
     *
     * @param lastUpdateTime the value for wd_user_site_total.last_update_time
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.last_update_person
     *
     * @return the value of wd_user_site_total.last_update_person
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.last_update_person
     *
     * @param lastUpdatePerson the value for wd_user_site_total.last_update_person
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson == null ? null : lastUpdatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.stat
     *
     * @return the value of wd_user_site_total.stat
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.stat
     *
     * @param stat the value for wd_user_site_total.stat
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_site_total.ip
     *
     * @return the value of wd_user_site_total.ip
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_site_total.ip
     *
     * @param ip the value for wd_user_site_total.ip
     *
     * @mbggenerated Thu Oct 09 15:57:05 CST 2014
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}