package com.wedding.user.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserEvaluateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public UserEvaluateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIdEqualTo(String value) {
            addCriterion("seller_id =", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotEqualTo(String value) {
            addCriterion("seller_id <>", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThan(String value) {
            addCriterion("seller_id >", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(String value) {
            addCriterion("seller_id >=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThan(String value) {
            addCriterion("seller_id <", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(String value) {
            addCriterion("seller_id <=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLike(String value) {
            addCriterion("seller_id like", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotLike(String value) {
            addCriterion("seller_id not like", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIn(List<String> values) {
            addCriterion("seller_id in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotIn(List<String> values) {
            addCriterion("seller_id not in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdBetween(String value1, String value2) {
            addCriterion("seller_id between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotBetween(String value1, String value2) {
            addCriterion("seller_id not between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaIsNull() {
            addCriterion("service_quota is null");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaIsNotNull() {
            addCriterion("service_quota is not null");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaEqualTo(Integer value) {
            addCriterion("service_quota =", value, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaNotEqualTo(Integer value) {
            addCriterion("service_quota <>", value, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaGreaterThan(Integer value) {
            addCriterion("service_quota >", value, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_quota >=", value, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaLessThan(Integer value) {
            addCriterion("service_quota <", value, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaLessThanOrEqualTo(Integer value) {
            addCriterion("service_quota <=", value, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaIn(List<Integer> values) {
            addCriterion("service_quota in", values, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaNotIn(List<Integer> values) {
            addCriterion("service_quota not in", values, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaBetween(Integer value1, Integer value2) {
            addCriterion("service_quota between", value1, value2, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andServiceQuotaNotBetween(Integer value1, Integer value2) {
            addCriterion("service_quota not between", value1, value2, "serviceQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaIsNull() {
            addCriterion("env_quota is null");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaIsNotNull() {
            addCriterion("env_quota is not null");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaEqualTo(Integer value) {
            addCriterion("env_quota =", value, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaNotEqualTo(Integer value) {
            addCriterion("env_quota <>", value, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaGreaterThan(Integer value) {
            addCriterion("env_quota >", value, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("env_quota >=", value, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaLessThan(Integer value) {
            addCriterion("env_quota <", value, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaLessThanOrEqualTo(Integer value) {
            addCriterion("env_quota <=", value, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaIn(List<Integer> values) {
            addCriterion("env_quota in", values, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaNotIn(List<Integer> values) {
            addCriterion("env_quota not in", values, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaBetween(Integer value1, Integer value2) {
            addCriterion("env_quota between", value1, value2, "envQuota");
            return (Criteria) this;
        }

        public Criteria andEnvQuotaNotBetween(Integer value1, Integer value2) {
            addCriterion("env_quota not between", value1, value2, "envQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaIsNull() {
            addCriterion("fun_price_quota is null");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaIsNotNull() {
            addCriterion("fun_price_quota is not null");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaEqualTo(Integer value) {
            addCriterion("fun_price_quota =", value, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaNotEqualTo(Integer value) {
            addCriterion("fun_price_quota <>", value, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaGreaterThan(Integer value) {
            addCriterion("fun_price_quota >", value, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("fun_price_quota >=", value, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaLessThan(Integer value) {
            addCriterion("fun_price_quota <", value, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaLessThanOrEqualTo(Integer value) {
            addCriterion("fun_price_quota <=", value, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaIn(List<Integer> values) {
            addCriterion("fun_price_quota in", values, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaNotIn(List<Integer> values) {
            addCriterion("fun_price_quota not in", values, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaBetween(Integer value1, Integer value2) {
            addCriterion("fun_price_quota between", value1, value2, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andFunPriceQuotaNotBetween(Integer value1, Integer value2) {
            addCriterion("fun_price_quota not between", value1, value2, "funPriceQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaIsNull() {
            addCriterion("prod_exp_quota is null");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaIsNotNull() {
            addCriterion("prod_exp_quota is not null");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaEqualTo(Integer value) {
            addCriterion("prod_exp_quota =", value, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaNotEqualTo(Integer value) {
            addCriterion("prod_exp_quota <>", value, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaGreaterThan(Integer value) {
            addCriterion("prod_exp_quota >", value, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("prod_exp_quota >=", value, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaLessThan(Integer value) {
            addCriterion("prod_exp_quota <", value, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaLessThanOrEqualTo(Integer value) {
            addCriterion("prod_exp_quota <=", value, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaIn(List<Integer> values) {
            addCriterion("prod_exp_quota in", values, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaNotIn(List<Integer> values) {
            addCriterion("prod_exp_quota not in", values, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaBetween(Integer value1, Integer value2) {
            addCriterion("prod_exp_quota between", value1, value2, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andProdExpQuotaNotBetween(Integer value1, Integer value2) {
            addCriterion("prod_exp_quota not between", value1, value2, "prodExpQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaIsNull() {
            addCriterion("dos_quota is null");
            return (Criteria) this;
        }

        public Criteria andDosQuotaIsNotNull() {
            addCriterion("dos_quota is not null");
            return (Criteria) this;
        }

        public Criteria andDosQuotaEqualTo(Integer value) {
            addCriterion("dos_quota =", value, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaNotEqualTo(Integer value) {
            addCriterion("dos_quota <>", value, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaGreaterThan(Integer value) {
            addCriterion("dos_quota >", value, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("dos_quota >=", value, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaLessThan(Integer value) {
            addCriterion("dos_quota <", value, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaLessThanOrEqualTo(Integer value) {
            addCriterion("dos_quota <=", value, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaIn(List<Integer> values) {
            addCriterion("dos_quota in", values, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaNotIn(List<Integer> values) {
            addCriterion("dos_quota not in", values, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaBetween(Integer value1, Integer value2) {
            addCriterion("dos_quota between", value1, value2, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andDosQuotaNotBetween(Integer value1, Integer value2) {
            addCriterion("dos_quota not between", value1, value2, "dosQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaIsNull() {
            addCriterion("excessive_quota is null");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaIsNotNull() {
            addCriterion("excessive_quota is not null");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaEqualTo(Integer value) {
            addCriterion("excessive_quota =", value, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaNotEqualTo(Integer value) {
            addCriterion("excessive_quota <>", value, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaGreaterThan(Integer value) {
            addCriterion("excessive_quota >", value, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("excessive_quota >=", value, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaLessThan(Integer value) {
            addCriterion("excessive_quota <", value, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaLessThanOrEqualTo(Integer value) {
            addCriterion("excessive_quota <=", value, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaIn(List<Integer> values) {
            addCriterion("excessive_quota in", values, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaNotIn(List<Integer> values) {
            addCriterion("excessive_quota not in", values, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaBetween(Integer value1, Integer value2) {
            addCriterion("excessive_quota between", value1, value2, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andExcessiveQuotaNotBetween(Integer value1, Integer value2) {
            addCriterion("excessive_quota not between", value1, value2, "excessiveQuota");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIsNull() {
            addCriterion("create_person is null");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIsNotNull() {
            addCriterion("create_person is not null");
            return (Criteria) this;
        }

        public Criteria andCreatePersonEqualTo(String value) {
            addCriterion("create_person =", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotEqualTo(String value) {
            addCriterion("create_person <>", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonGreaterThan(String value) {
            addCriterion("create_person >", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonGreaterThanOrEqualTo(String value) {
            addCriterion("create_person >=", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLessThan(String value) {
            addCriterion("create_person <", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLessThanOrEqualTo(String value) {
            addCriterion("create_person <=", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLike(String value) {
            addCriterion("create_person like", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotLike(String value) {
            addCriterion("create_person not like", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIn(List<String> values) {
            addCriterion("create_person in", values, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotIn(List<String> values) {
            addCriterion("create_person not in", values, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonBetween(String value1, String value2) {
            addCriterion("create_person between", value1, value2, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotBetween(String value1, String value2) {
            addCriterion("create_person not between", value1, value2, "createPerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonIsNull() {
            addCriterion("last_update_person is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonIsNotNull() {
            addCriterion("last_update_person is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonEqualTo(String value) {
            addCriterion("last_update_person =", value, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonNotEqualTo(String value) {
            addCriterion("last_update_person <>", value, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonGreaterThan(String value) {
            addCriterion("last_update_person >", value, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonGreaterThanOrEqualTo(String value) {
            addCriterion("last_update_person >=", value, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonLessThan(String value) {
            addCriterion("last_update_person <", value, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonLessThanOrEqualTo(String value) {
            addCriterion("last_update_person <=", value, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonLike(String value) {
            addCriterion("last_update_person like", value, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonNotLike(String value) {
            addCriterion("last_update_person not like", value, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonIn(List<String> values) {
            addCriterion("last_update_person in", values, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonNotIn(List<String> values) {
            addCriterion("last_update_person not in", values, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonBetween(String value1, String value2) {
            addCriterion("last_update_person between", value1, value2, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andLastUpdatePersonNotBetween(String value1, String value2) {
            addCriterion("last_update_person not between", value1, value2, "lastUpdatePerson");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 05 21:08:33 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_user_evaluate
     *
     * @mbggenerated Sun Oct 05 21:08:33 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}